cache:
  directories:
    - node_modules
script:
  - npm run build
branches:
  only:
    - master
after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push giangbuiquang/aatest