language: node_js
"-node_js":
- v12.15.0
cache:
  directories:
  - node_modules

before_install:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
    -in .travis/deploy_rsa.enc -out .travis/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - cp .travis/id_rsa ~/.ssh/deploy_rsa
  - chmod 600 ~/.ssh/deploy_rsa
  - ssh-add ~/.ssh/deploy_rsa
script:
- npm run build
- docker build -t giangbuiquang/aatest:1.0 .
branches:
  only:
  - developer
  - master
after_success:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker push giangbuiquang/aatest:1.0

deploy:
  - provider: script
    script: bash .travis/deploy.sh
    on:
      branch: developer
addons:
  ssh_known_hosts:
  - $REMOTE_HOST
install:
  - echo '$REMOTE_HOST' >> $HOME/.ssh/known_hosts
  # - provider: script
  #   script: deploy_staging.sh
  #   on:
  #     branch: staging
