language: node_js
"-node_js":
- v12.15.0
cache:
  directories:
  - node_modules
addons:
  ssh_known_hosts: $REMOTE_HOST

before_install:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
    -in .travis/deploy_rsa.enc -out .travis/deploy_rsa -d
# script:
# - npm run build
# - docker build -t giangbuiquang/aatest:1.0 .
# branches:
#   only:
#   - developer
#   - master

# after_success:
# - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
# - docker push giangbuiquang/aatest:1.0

jobs:
  include:
    # - stage: build docker image
    #   script:
    #   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    #   - docker build -t travis-ci-build-stages-demo .
    #   - docker images
    #   - docker tag travis-ci-build-stages-demo $DOCKER_USERNAME/travis-ci-build-stages-demo
    #   - docker push $DOCKER_USERNAME/travis-ci-build-stages-demo
    - stage: development
      branch: developer
      script:
        - npm run build
        - docker build -t giangbuiquang/aatest:development .
      after_success:
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - docker push giangbuiquang/aatest:development
      deploy:
        - provider: script
          script: bash .travis/deploy.sh
          on:
            branch: developer

    - stage: production
      branch: master
      script:
        - npm run build
        - docker build -t giangbuiquang/aatest:production .
      after_success:
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - docker push giangbuiquang/aatest:production
      
        # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    #   script: docker run --rm $DOCKER_USERNAME/travis-ci-build-stages-demo cat hello.txt
    # - script: docker run --rm $DOCKER_USERNAME/travis-ci-build-stages-demo cat hello.txt



  # - provider: script
  #   script: deploy_staging.sh
  #   on:
  #     branch: staging
