language: node_js
-node_js: 
  - "v12.15.0"
cache:
  directories:
    - node_modules
script:
  - npm run build
  - docker build -t giangbuiquang/aatest:1.0 .
branches:
  only:
    - master
after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push giangbuiquang/aatest:1.0